import Head from 'next/head'
import styles from '@/styles/App.module.css'
import Examples from '@/components/examples'
import About from '@/components/about'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <About />
        <Examples />
      </div>
    </>
  )
}
